name: Test Stable

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.12
      - name: Install dependencies
        run: |
          curl -sSL https://install.python-poetry.org | python -
          poetry self add poetry-multiproject-plugin
          poetry self add poetry-polylith-plugin
          poetry install
      - name: Run tests
        run: |
          poetry run pytest
